GRANT SELECT ON public.defn TO PUBLIC;
GRANT SELECT ON public.meta TO PUBLIC;
GRANT SELECT ON public.multi TO PUBLIC;
GRANT SELECT ON public.mwe_components TO PUBLIC;
GRANT SELECT ON public.mwe_type TO PUBLIC;
GRANT SELECT ON public.qry TO PUBLIC;
GRANT SELECT ON public.qrya TO PUBLIC;
GRANT SELECT ON public.revision TO PUBLIC;

GRANT CREATE ON DATABASE erg TO PUBLIC;

GRANT INSERT ON public.meta TO PUBLIC;
