(((:path . "harmony") (:content . "LOGON Harmonization Test Suite"))
 ((:path . "hike") (:content . "LOGON First Development Corpus"))
 ((:path . "rondane") (:content . "LOGON Hiking Treebank (Rondane)"))
 ((:path . "shiken") (:content . "LOGON Embryonic JaEn MT Test Suite"))
 ((:path . "jhpstg") (:content . "LOGON Development Corpus (All Segments)"))
 ((:path . "jh") (:content . "LOGON Jotunheimen Corpus (All Sections)"))
 ((:path . "jh0") (:content . "LOGON Jotunheimen Corpus (Section 0)"))
 ((:path . "jh1") (:content . "LOGON Jotunheimen Corpus (Section 1)"))
 ((:path . "jh2") (:content . "LOGON Jotunheimen Corpus (Section 2)"))
 ((:path . "jh3") (:content . "LOGON Jotunheimen Corpus (Section 3)"))
 ((:path . "jh4") (:content . "LOGON Jotunheimen Corpus (Section 4)"))
 ((:path . "jh5") (:content . "LOGON Jotunheimen Corpus (Section 5)"))
 ((:path . "jhk") (:content . "LOGON Jotunheimen Test Corpus (Known-Vocabulary)"))
 ((:path . "jhu") (:content . "LOGON Jotunheimen Test Corpus (Unknown-Vocabulary)"))
 ((:path . "ps") (:content . "LOGON Preikestolen Corpus"))
 ((:path . "psk") (:content . "LOGON Preikestolen Test Corpus (Known-Vocabulary)"))
 ((:path . "psu") (:content . "LOGON Preikestolen Test Corpus (Unknown-Vocabulary)"))
 ((:path . "tg") (:content . "LOGON Turglede Corpus (All Sections)"))
 ((:path . "tg1") (:content . "LOGON Turglede Corpus (Section 1)"))
 ((:path . "tg2") (:content . "LOGON Turglede Corpus (Section 2)"))
 ((:path . "tgk") (:content . "LOGON Turglede Test Corpus (Known-Vocabulary)"))
 ((:path . "tgu") (:content . "LOGON Turglede Test Corpus (Unknown-Vocabulary)")))
