(((:path . "ws01") (:content . "WeScience Articles 1 -- 4"))
 ((:path . "ws02") (:content . "WeScience Articles 5 -- 15"))
 ((:path . "ws03") (:content . "WeScience Articles 16 -- 23"))
 ((:path . "ws04") (:content . "WeScience Articles 24 -- 28"))
 ((:path . "ws05") (:content . "WeScience Articles 29 -- 31"))
 ((:path . "ws06") (:content . "WeScience Articles 32 -- 37"))
 ((:path . "ws07") (:content . "WeScience Articles 38 -- 42"))
 ((:path . "ws08") (:content . "WeScience Articles 43 -- 48"))
 ((:path . "ws09") (:content . "WeScience Articles 49 -- 55"))
 ((:path . "ws10") (:content . "WeScience Articles 56 -- 63"))
 ((:path . "ws11") (:content . "WeScience Articles 64 -- 70"))
 ((:path . "ws12") (:content . "WeScience Articles 71 -- 78"))
 ((:path . "ws13") (:content . "WeScience Articles 79 -- 88"))
 ((:path . "ws14") (:content . "WeScience Articles 89 -- 91 (Evaluation)"))
 ((:path . "ws15") (:content . "WeScience Articles 92 -- 96 (Evaluation)"))
 ((:path . "ws16") (:content . "WeScience Articles 97 -- 100 (Evaluation)")))
 
