(((:path . "dnt.activity") (:content . "HandOn Corpus from DNT Activities"))
 ((:path . "dnt.article") (:content . "HandOn Corpus from DNT Articles"))
 ((:path . "dnt.cabin") (:content . "HandOn Corpus from DNT Cabins"))
 ((:path . "dnt.index") (:content . "HandOn Corpus from DNT Overview"))
 ((:path . "dnt.location") (:content . "HandOn Corpus from DNT Areas"))
 ((:path . "dnt.trip") (:content . "HandOn Corpus from DNT Trips"))
 ((:path . "guide.general") (:content . "HandOn Corpus from Willassen Overview"))
 ((:path . "guide.location") (:content . "HandOn Corpus from Willassen Areas"))
 ((:path . "bike") (:content . "HandOn Corpus from http://www.bike-norway.com"))
 ((:path . "gol") (:content . "HandOn Corpus from http://www.golinfo.no"))
 ((:path . "romsdal") (:content . "HandOn Corpus from http://www.romsdalsalpene.no"))
 ((:path . "tiltopps") (:content . "HandOn Corpus from http://www.tilltopps.com"))
 ((:path . "turistveg") (:content . "HandOn Corpus from http://www.turistveg.no")))
