#!/bin/bash

ROOT=/lingo/www/aserve
GRAMMAR=erg
PORT=8000

if [ ! -z "${1}" ]; then 
  GRAMMAR=${1} ]; 
fi

if [ ! -z "${2}" ]; then 
  PORT=${2} ]; 
fi

LOG=${ROOT}/${GRAMMAR}.log

unset DISPLAY

{
  date
  echo $GRAMMAR @ $PORT
  ( \
    echo "(load \"${ROOT}/dot.clinit.cl\")"; \
    echo "(load \"${ROOT}/lkb/src/general/loadup.lisp\")"; \
    echo "(pushnew :lkb *features*)"; \
    echo "(setf (system:getenv \"DISPLAY\") nil)"; \
    echo "(compile-system \"www\" :force t)"; \
    echo "(setf lkb::*www-maximal-number-of-edges* 10000)"; \
    echo "(tsdb::initialize-tsdb nil :rc \"${ROOT}/dot.tsdbrc\")"; \
    echo "(tsdb:tsdb :home \"${ROOT}/lkb/src/tsdb/home\")"; \
    echo "(read-script-file-aux \"${ROOT}/${GRAMMAR}/lkb/script\")"; \
    echo "(tsdb:tsdb :cpu :www :file t :count 4)"; \
    echo "(tsdb:tsdb :cpu)"; \
    echo "(www::initialize :port ${PORT})"; \
    cat - \
  )  | ( cd /lingo/local/acl; ./alisp -I bclim.dxl -qq; )

} 2>&1 | tee -a ${LOG}
