#!/bin/bash

if [ -z "${DELPHINHOME}" ]; then
  DELPHINHOME=${HOME}/delphin
fi
TSDBHOME=${DELPHINHOME}/lkb/src/tsdb/home
TARGET=${DELPHINHOME}/tmp
TSDB=${DELPHINHOME}/lkb/bin/linux.x86.32/tsdb
GRAMMAR=${DELPHINHOME}/erg.jun-04

[ -d ${TARGET} ] || mkdir $TARGET;
[ -d ${TSDBHOME}/log ] || mkdir ${TSDBHOME}/log;

log="$(echo ${1} | sed "s@/@.@g")"

if [ ! -z "${2}" ]; then
  extra="${2}";
fi

increment=200;
if echo ${1} | egrep "ecoc|ecos|ecpa|ecpr" > /dev/null; then
  increment=100000;
fi

unset DISPLAY

{
  low=0;
  DB=${TSDBHOME}/${1}
  all=$(${TSDB} -home ${DB} -query 'select i-id from item' \
        | sort -n | tail -1);

  while [ ${low} -le ${all} ]; do
    high=$[${low} + ${increment}];
    echo
    echo "exporting \`${1}' [$low -- $high]";
    echo
    condition="i-id >= ${low} && i-id < ${high}";
    if [ ! -z "${extra}" ]; then
      condition="${condition} && (${extra})";
    fi
    condition="${condition} && (readings >= 1 && t-active == 1)";
    low=${high};

    ( \
      echo "(system:resize-areas :old (* 128 1024 1024) "; \
      echo "                     :new (* 256 1024 1024))"; \
      echo "(setf (sys:gsgc-switch :print) t)"; \
      echo "(setf (sys:gsgc-switch :stats) t)"; \
      echo "(setf (sys:gsgc-switch :verbose) t)"; \
      echo "(setf (sys:gsgc-parameter :auto-step) nil)"; \
 
      echo "(setf (system:getenv \"DISPLAY\") nil)"; \
      echo "(load \"${DELPHINHOME}/lkb/src/general/itsdb.lisp\")"; \

      echo "(setf mrs::*eds-include-quantifiers-p* nil)"; \
      echo "(setf mrs::*eds-include-vacuous-relations-p* nil)"; \
      echo "(setf tsdb::*redwoods-export-values* :all)"; \
      echo "(setf tsdb::*redwoods-thinning-export-p* nil)"; \
      echo "(lkb:read-script-file-aux \"${GRAMMAR}/lkb/script\")"; \

      echo "(excl:gc :tenure) (excl:gc t) (excl:gc)"; \

      echo "(tsdb:tsdb :home \"$TSDBHOME\")"; \
      echo "(tsdb::export-trees \"${1}\" :path \"${TARGET}\""; \
      echo "  :condition \"${condition}\")"; \
      echo "(excl:exit)"; \
    ) | ${DELPHINHOME}/bin/lkb -qq
  done
} 2>&1 | tee ${TSDBHOME}/log/${log}.$$.log
