(in-package "COMMON-LISP-USER")

(defpackage "PVM"
  (:use "COMMON-LISP" "FF" "MAKE")
  (:export
   "%PVM_NO_PARENT%" "%PVM_TASK_FAIL%" "%PVM_LISP_MESSAGE%" 
   "*PVM-DEBUG-P*" "*PVM-PENDING-EVENTS*" 
   "MAKE-CPU" "CPU-P" "CPU-HOST" "CPU-SPAWN" "CPU-OPTIONS" "CPU-INITIALIZE"
   "CPU-ARCHITECTURE" "CPU-CLASS" "CPU-THRESHOLD" 
   "MAKE-TASK" "TASK-P" "TASK-TID" "TASK-TASK" "TASK-CPU" 
   "TASK-FORM" "TASK-STATUS" 
   "PVM_REGISTER" "PVM_QUIT" "PVM_START" "PVM_KILL" "PVM_PARENT" 
   "PVM_CREATE" 
   "PVM_POLL" "PVM_TRANSMIT" 
   "PVM_TIDTOHOST" "PVM_VM_INFO" "PVM_TASK_INFO" 
   "MESSAGE-P" 
   "MESSAGE-TAG" "MESSAGE-REMOTE" "MESSAGE-CONTENT" "MESSAGE-CORPSE" 
   "SHUTDOWN" 
   "TID-STATUS" "REVALUATE"))
